import numpy as np
import matplotlib.pyplot as plt

plt.figure()
plt.rc('font', size=14)
plt.locator_params(nbins=6)
c = np.exp(1)
c2 = np.exp(2)
c3 = np.exp(3)
x = np.linspace(0,10,1000)
xi = 1
a = np.exp(x)
plt.plot(x, np.log((a+a*c*xi)/2 + ((a+a*c*xi)**2/4 - a*c*xi)**(1/2)), lw = 2, color = 'k')
plt.plot(x, x, lw = 2, color = 'k', alpha = 0.7)
plt.fill_between(x, x, np.log((a+a*c*xi)/2 + ((a+a*c*xi)**2/4 - a*c*xi)**(1/2)), color = 'c')
plt.xlim(x[0],x[-1])
plt.ylim(x[0],x[-1])
plt.xlabel('$-\Delta\epsilon_N$')
plt.ylabel('$-\Delta\epsilon_G$')
plt.ticklabel_format(scilimits=None, useOffset=None, useLocale=None, useMathText=True)
plt.show()

plt.figure()
plt.rc('font', size=14)
plt.locator_params(nbins=6)
plt.plot(a, (a+a*c*xi)/2 + ((a+a*c*xi)**2/4 - a*c*xi)**(1/2), lw = 2, color = 'k')
plt.plot(a, a, lw = 2, color = 'k', alpha = 0.7)
plt.fill_between(a, a, (a+a*c*xi)/2 + ((a+a*c*xi)**2/4 - a*c*xi)**(1/2), color = 'c')
plt.xlim(a[0],a[-1])
plt.ylim(a[0],a[-1])
plt.xlabel('$a$')
plt.ylabel('$b$')
plt.ticklabel_format(scilimits=[1,0], useOffset=None, useLocale=None, useMathText=True)
plt.show()